#!/bin/bash

if type >/dev/null -t oowriter; then
    exec oowriter
fi

if type >/dev/null -t soffice; then
    exec soffice
fi

if type >/dev/null -t abiword-2.2; then
    exec abiword-2.2
fi

exec abiword
