# I den här filen kan du lägga kommandon som du vill ska utföras när
# fönstersystemet startar. T.ex. starta en klocka, lägga upp en 
# roligare bakgrundsbild etc.

# Några exempel. (Ta bort kommentarstecknet (#) i början av raden om du 
# vill att raden ska utföras.)

# starta en klocka i nedre högra hörnet av skärmen:
#dxclock -geometry 170x70-10-10 &

# Visa en fin bakgrundsbild:
#xv -root -rmode 5 -maxpect -quit /misc/graphics/misc/lighthouse.gif &
